### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by fundon** [vue-bulma/pagination#1]
Welcome @netpi. Thanks to join the team.

Could you change the repo name? Named `pagination` will be better.

/cc @luventa

**Comment by netpi** [comment]
It is my pleasure to coding with you @fundon and @luventa  😄 .

the action to setting repo need admin permision . @fundon u may help to change repo name 

![image](https://cloud.githubusercontent.com/assets/8254020/23576444/5d25d97a-00e0-11e7-836b-7441ef18e9e8.png)

**Comment by fundon** [comment]
Done.
