### ISSUE TITLE
Slash hard coded in urlPrefix

### ISSUE THREAD

**Issue by silver8ack** [vue-bulma/pagination#11]
Can you remove the slash that is hard coded in the urlPrefix?

**Comment by netpi** [comment]
@silver8ack ok i will fix it soon

**Comment by netpi** [comment]
https://github.com/vue-bulma/pagination/pull/13

**Comment by netpi** [comment]
@silver8ack  you mean https://github.com/vue-bulma/pagination/pull/13 ?

**Comment by silver8ack** [comment]
@netpi Yes, that's the same request I had.  I was trying to use a query parameter for the page number, but the slash was messing it up.

Thanks.

**Comment by netpi** [comment]
@silver8ack check new docs
