### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by moonlik** [vue-bulma/pagination#3]
Hi! I can't make this component work with Vue 2.2.1 and vue-router 2.3.0.

```
Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (app.js:1488)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1134), <anonymous>:11:27)
    at Object.<anonymous> (app.js:1134)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1512), <anonymous>:7:3)
    at Object.<anonymous> (app.js:1512)
    at __webpack_require__ (app.js:556)
```

![monosnap 2017-03-09 18-24-44](https://cloud.githubusercontent.com/assets/19203280/23746121/c383d532-04f5-11e7-9244-7281aa2dcfa3.png)

**Comment by moonlik** [comment]
The problem was with index.js. I replaced
```
"main": "src/index.js",
```
with
```
"main": "src/Pagination.vue",
```
in package.json.

Now I get another problem:
```
[Vue warn]: Invalid prop: type check failed for prop "currentPage". Expected Number, got String. 
(found in <VueBulmaPagination> at /node_modules/vue-bulma-pagination/src/Pagination.vue)

[Vue warn]: Invalid prop: type check failed for prop "pageLength". Expected Number, got String. 
(found in <VueBulmaPagination> at /node_modules/vue-bulma-pagination/src/Pagination.vue)
```

Even if I manually input integers:
```
<pagination urlPrefix='?page=' currentPage="2" pageLength="5" />
```

**Comment by luventa** [comment]
for the import issue, I think you need this:
Add exclude: [new RegExp(`node_modules\\${path.sep}(?!vue-bulma-.*)`)] to your webpack babel loader config.

Example here: https://github.com/vue-bulma/vue-admin/blob/master/build/webpack.base.conf.js#L65

**Comment by moonlik** [comment]
For this problem:
```
<pagination urlPrefix='?page=' currentPage="2" pageLength="5" />
```
You should correct the example, because it's necessary to write colon before urLPrefix etc. as follow:
```
<pagination :urlPrefix="'?page='" :currentPage="2" :pageLength="5" />
```

**Comment by netpi** [comment]
@moonlik  thank you moonlik i agree  to write a colon .  however the the page number that jump to will be automatically added

**Comment by netpi** [comment]
@moonlik 
I have update to a new version 1.1.0  https://github.com/vue-bulma/pagination/pull/4/commits/d0117148c06cc5c88ef9945b6e9a5c1216aa04b1

and u can visit this page [ItemList.vue#L7 ]( https://github.com/beauty-enjoy/beauty/blob/master/src/components/ItemList.vue#L7 ) for more using detail

**Comment by netpi** [comment]
done.

**Comment by netpi** [comment]
done.
